name: scale_x_registry
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  args: ^2.3.1
  http: ^0.13.5
  path: ^1.8.2
  shelf: ^1.4.0
  shelf_hotreload: ^1.4.0
  shelf_router: ^1.1.3
  sqlite3: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
